assgn_2/mysite/flights/urls.py
from django.urls import path

from . import views

app_name = 'flights'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('search', views.SearchView, name='search'),
    path('airlines', views.AirlinesView.as_view(), name='airlines'),
    path('airports', views.AirportsView.as_view(), name='airports'),
    path('locations', views.LocationsView.as_view(), name='locations'),
    path('setcustomer/<int:customer_id>', views.setcustomer, name='setcustomer'),
    path('bookings', views.BookingsView, name='bookticket')
]

assgn_2/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('flights/', include('flights.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

assgn_2/mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

assgn_2/mysite/flights/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Location(models.Model):
	loc_id=models.CharField(max_length=5 ,primary_key=True)
	state=models.CharField(max_length=30)
	country=models.CharField(max_length=30)
	zip_code=models.CharField(max_length=10)

	def __str__(self):
		return self.state + ", " + self.country + ", " + self.zip_code

class Airline(models.Model):
	airline_id=models.CharField(max_length=10 ,primary_key=True)
	name=models.CharField(max_length=30)
	is_charter=models.BooleanField(default=False)
	upload = models.ImageField(upload_to ='static/airlines/',null=True) 

	def __str__(self):
		return "["+self.airline_id+"] " + self.name


class Flight(models.Model):
	flight_id=models.CharField(max_length=10 ,primary_key=True)
	airline=models.ForeignKey(Airline, on_delete=models.CASCADE)
	seats=models.IntegerField()

	def __str__(self):
		return "[{}] {}".format(self.airline.airline_id, 	self.flight_id)

class Airport(models.Model):
	airport_id=models.CharField(max_length=10 ,primary_key=True)
	name=models.CharField(max_length=50)
	code=models.CharField(max_length=15)
	location=models.ForeignKey(Location, on_delete=models.CASCADE)

	def __str__(self):
		return "[{}] {}".format(self.airport_id, self.name)

class Schedule(models.Model):
	schedule_id=models.CharField(max_length=10 ,primary_key=True)
	flight=models.ForeignKey(Flight,on_delete=models.CASCADE)
	src_air=models.ForeignKey(Airport,on_delete=models.CASCADE, related_name='src_air' )
	des_air=models.ForeignKey(Airport, on_delete=models.CASCADE,related_name='des_air')
	fare=models.DecimalField(max_digits=10,decimal_places=2)
	start_time=models.DateTimeField()
	end_time=models.DateTimeField()

	def __str__(self):
		return "{} {}".format(self.flight,self.start_time)

class Customer(models.Model):
	Gen = (
		('male','male'),
		('female','female'),
		)
	cust_id=models.IntegerField(primary_key=True)
	name=models.CharField(max_length=30)
	age=models.IntegerField()
	address=models.TextField()
	location=models.ForeignKey(Location, on_delete=models.CASCADE)
	gender=models.CharField(max_length = 8, choices = Gen)
	email=models.EmailField(max_length=50)
	phone=models.CharField(max_length=20)

	def __str__(self):
		return "[{}] {}".format(self.cust_id, self.name)

class Booking(models.Model):
	schedule=models.ForeignKey(Schedule, on_delete=models.CASCADE)
	customer=models.ForeignKey(Customer, on_delete=models.CASCADE)
	price=models.DecimalField(max_digits=10,decimal_places=2)

	def __str__(self):
		return self.schedule + " " + self.customer

assgn_2/mysite/flights/views.py
from django.shortcuts import render
from django.http import JsonResponse
# Create your views here.
from django.shortcuts import render,get_object_or_404
from django.http import Http404
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from .models import Airline,Schedule,Location,Airport,Customer, Booking
from collections import defaultdict

class IndexView(generic.ListView):
    template_name = 'flights/index.html'
    context_object_name = 'airlines'

    def get_queryset(self):
        return Airline.objects.all()

def SearchView(request):
    context={'form_data':{'max_price':50000}}
    if(request.POST):
        form_data = request.POST
        context['form_data'] = form_data
        query_set = Schedule.objects.filter(src_air=form_data['src_air_id'],des_air=form_data['dest_air_id'])
        if form_data['start_date']:
            query_set = query_set.filter(start_time__gte=form_data['start_date'])
        if form_data['end_date']: 
            query_set = query_set.filter(end_time__lte=form_data['end_date'])
        if form_data['max_price']: 
            query_set = query_set.filter(fare__lte=form_data['max_price'])
        context['flights'] = query_set.all()
    return render(request,'flights/search.html',context)

class AirlinesView(generic.ListView):
    template_name = 'flights/airlines.html'
    context_object_name = 'airlines'

    def get_queryset(self):
        return Airline.objects.all()

class AirportsView(generic.ListView):
    template_name = 'flights/airports.html'
    context_object_name = 'airports'

    def get_queryset(self):
        return Airport.objects.all()

class LocationsView(generic.ListView):
    template_name = 'flights/locations.html'
    context_object_name = 'locations'

    def get_queryset(self):
        for location in Location.objects.all():
            print(dir(location))
        return Location.objects.all()

def setcustomer(request, customer_id):
    customer = get_object_or_404(Customer, pk=customer_id)
    request.session['customer'] = customer_id
    return JsonResponse({"error":False,"message":"Customer updated to "+str(customer)})

def BookingsView(request):
    context={}
    if(request.POST):
        customer = get_object_or_404(Customer, pk=request.session['customer'])
        schedule = get_object_or_404(Schedule, pk=request.POST['schedule_id'])
        booking = Booking(customer=customer,schedule=schedule,price=schedule.fare)
        booking.save()

    bookings = Booking.objects.all()

    customer_wise_bookings = defaultdict(lambda: [])
    for booking in bookings:
        customer_wise_bookings[booking.customer].append(booking.schedule)
    context['bookings'] = customer_wise_bookings.items()
    context['sql'] = bookings.query

    return render(request,'flights/bookings.html',context)

assgn_2/mysite/flights/templates/flights/airlines.html
{% extends 'flights/base.html' %}
{% load static%}
{% load flight_inputs %}

{% block content%}
	<div class="uk-container">
		<br>
    	<pre><code class="sql"> {{airlines.query | sql_format}} </code></pre>
		{% for airline in  airlines %}
			<article class="uk-article">
			    <h1 class="uk-article-title">{{airline.name}}</h1>
			    {% for flight in airline.flight_set.all %}
			    	{% flights_table flight.schedule_set.all %}
			    {% empty %}
			    	<div class="uk-text-center">No Flights At the Moment</div>
			    {% endfor %}
			</article>
		{% endfor %}
	</div>
	<br>
{% endblock %}

assgn_2/mysite/flights/templates/flights/airport_dropdown.html
<div class="uk-margin">
    <label class="uk-form-label" for="form-stacked-select"> {{label}} </label>
    <div class="uk-form-controls">
        <select class="uk-select uk-border-rounded" name="{{name}}">
        	{% for airport in airports %}
			    <option class="truncate" value="{{airport.airport_id}}" 
			    	{% if  airport.airport_id == value %}
					    selected 
					{% endif %}
			    > {{airport}} </option>
			{% endfor %}
        </select>
    </div>
</div>

assgn_2/mysite/flights/templates/flights/airports.html
{% extends 'flights/base.html' %}
{% load static%}
{% load flight_inputs %}

{% block content%}
  <div class="uk-container">
    <br>
    <pre><code class="sql"> {{airports.query | sql_format}} </code></pre>

    {% for airline in  airports %}
      <article class="uk-article">
          <h1 class="uk-article-title">{{airline.name}}</h1>
          <h3>Departure</h3>
          {% flights_table airline.src_air.all %}
          <h3>Arrival</h3>
          {% flights_table airline.des_air.all %}
      </article>
    {% endfor %}
  </div>
  <br>
{% endblock %}

assgn_2/mysite/flights/templates/flights/base.html
{% load static %}
{% load flight_inputs %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flights on board</title>
    <link rel="icon" href="{% static "img/favicon.svg"%}">
    <!-- CSS FILES -->
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/uikit@latest/dist/css/uikit.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Work+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static "css/style.css"%}">
    <link rel="stylesheet" href="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.2.0/build/styles/atom-one-light.min.css">
    <script src="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.2.0/build/highlight.min.js"></script>
    {% block header_css %}{% endblock %}
  </head>
  <body>
    <!-- TOP -->
    <div class="top-wrap uk-position-relative uk-light uk-background-secondary" style="border-bottom: 1px solid gray">      
      <!-- NAV -->
      <div class="nav" data-uk-sticky="cls-active: uk-background-secondary uk-box-shadow-medium; top: 100vh; animation: uk-animation-slide-top">
        <div class="uk-container">
          <nav class="uk-navbar uk-navbar-container uk-navbar-transparent" data-uk-navbar>
            <div class="uk-navbar-left">
              <div class="uk-navbar-item uk-padding-remove-horizontal">
                <a class="uk-logo" title="Logo" href="/flights">
                  <i uk-icon="bolt"></i> Flights on Board
                </a>
              </div>
            </div>
            <div class="uk-navbar-right">
              <ul class="uk-navbar-nav uk-visible@s">
                <li><a href="{% url 'flights:search' %}">Search</a></li>
                <li>
                  <a href="#" data-uk-icon="chevron-down">View</a>
                  <div class="uk-navbar-dropdown">
                    <ul class="uk-nav uk-navbar-dropdown-nav">
                      <li><a href="{% url 'flights:airports' %}">Airports</a></li>
                      <li><a href="{% url 'flights:airlines' %}">Airlines</a></li>
                      <li><a href="{% url 'flights:locations' %}">Locations</a></li>
                    </ul>
                  </div>
                </li>
                <li><a href="/flights/bookings">Bookings</a></li>
                <li>
                  {% customer_dropdown request.session.customer %}
                </li>
              </ul>
              <a class="uk-navbar-toggle uk-navbar-item uk-hidden@s" data-uk-toggle data-uk-navbar-toggle-icon href="#offcanvas-nav"></a>
            </div>
          </nav>
        </div>
      </div>
    </div>
      <!-- /NAV -->
    {% block content %}{% endblock %}

     <!-- FOOTER -->
    <footer class="uk-section uk-section-secondary">
      <div class="uk-container">
          <div class="uk-text-right">
            <h5>Flight on Board 2020</h5>
          </div>
      </div>
    </footer>
    <!-- /FOOTER -->
    <!-- JS FILES -->
    <script src="https://cdn.jsdelivr.net/npm/uikit@latest/dist/js/uikit.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/uikit@latest/dist/js/uikit-icons.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
  </body>
</html>

assgn_2/mysite/flights/templates/flights/bookings.html
{% extends 'flights/base.html' %}
{% load static%}
{% load flight_inputs %}

{% block content%}
<br/>
  <div class="uk-container">
    <h1>Bookings</h1>
    <pre><code class="sql"> {{sql | sql_format}} </code></pre>
    {% for customer,booking in  bookings %}
      <article class="uk-article">
          <h3 class="uk-article-title">{{customer.name}}</h3>
          {% flights_table booking 'Hide'%}
      </article>
    {% endfor %}
  </div>
<br/>
{% endblock %}

assgn_2/mysite/flights/templates/flights/customer_dropdown.html
<div class="uk-margin">
	<script>
		function status(response) {
		  if (response.status >= 200 && response.status < 300) {
		    return Promise.resolve(response)
		  } else {
		    return Promise.reject(new Error(response.statusText))
		  }
		}

		function json(response) {
		  return response.json()
		}

		function onCustomerSelect(elem){
			fetch("/flights/setcustomer/"+elem.options[elem.selectedIndex].value).then(status).then(json).then(function(data){
				UIkit.notification({message: "<span uk-icon=\'icon: check\'></span> "+data.message})
			});
		}
	</script>
    <label class="uk-form-label uk-text-muted" for="form-stacked-select"> Active Customer</label>
	<div class="uk-form-controls">
	    <select onchange="onCustomerSelect(this)" class="uk-select uk-border-rounded" name="{{name}}">
	    	{% for customer in customers %}
			    <option class="truncate" value="{{customer.cust_id}}" 
			    	{% if  customer.cust_id == active_customer %}
					    selected 
				{% endif %}
			    > {{customer}} </option>
			{% endfor %}
	    </select>
	</div>
</div>

assgn_2/mysite/flights/templates/flights/flights_table.html
{% for flight in flights %}
	<div>
		<div class="uk-card uk-card-default">
			<div class="uk-card-header uk-text-center">
		        <div class="uk-grid-small" uk-grid>
		        	<div class="uk-width-auto">
		        		<img width="50" height="50" src="/{{flight.flight.airline.upload}}">
		        	</div>
				    <div class="uk-width-1-6 uk-text-center">
				    	    <h3 class="uk-card-title uk-margin-remove-bottom">{{flight.flight.airline.name}}</h3>
		                	<p class="uk-text-meta uk-margin-remove-top">{{flight.flight.flight_id}}</p>
				    </div>
				    <div class="uk-width-1-6 uk-text-center">
				    	    <h3 class="uk-card-title uk-margin-remove-bottom">{{flight.src_air.location.state}}</h3>
		                	<p class="uk-text-meta uk-margin-remove-top truncate">{{flight.src_air.name}}</p>
				    </div>
				    <span uk-icon="icon: arrow-right; ratio: 1.7" style="padding:0;margin-right: -17px;margin-left: -17px"></span>
				    <div class="uk-width-1-6 uk-text-center">
				    	    <h3 class="uk-card-title uk-margin-remove-bottom">{{flight.des_air.location.state}}</h3>
		                	<p class="uk-text-meta uk-margin-remove-top truncate">{{flight.des_air.name}}</p>
				    </div>
				    <div class="uk-width-1-6 uk-text-center">
				    	    <h3 class="uk-card-title uk-margin-remove-bottom">{{flight.start_time | date:'H:i' }} - {{flight.end_time | date:'H:i' }}</h3>
		                	<p class="uk-text-meta uk-margin-remove-top truncate">
		                		{{ flight.start_time|date:'d M' }}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ flight.end_time|date:'d M' }}
		                	</p>
				    </div>
					<div class="uk-width-1-6 uk-text-center">
						<h3 class="uk-card-title uk-margin-remove-bottom">{{flight.fare}}</h3>
						<p class="uk-text-meta uk-margin-remove-top truncate">INR</p>
				    </div>
				    {% if not hide_booking %}
				    <div class="uk-width-auto">
		        		<form method="POST" action="/flights/bookings">
		        			{% csrf_token %}
		        			<input type="hidden" name="schedule_id" value="{{flight.schedule_id}}"/>
		        			<button class="uk-button uk-button-primary uk-border-rounded">Book</button>
		        		</form>
		        	</div>
		        	{% endif %}
		        </div>
		    </div>
		</div>
	</div>

{% empty %} 
	No Flights at the moment
{% endfor %} 

assgn_2/mysite/flights/templates/flights/index.html
{% extends 'flights/base.html' %}
{% load static%}
{% load flight_inputs %}
{% block header_css %}
	<link rel="stylesheet" type="text/css" href="{% static "css/marketing.css"%}">
{% endblock %}
{% block content%}
    <section class="uk-section uk-section-secondary uk-section-small">
      <div class="uk-container">
        <div class="uk-grid uk-child-width-1-2@l uk-flex-middle">
          <div>
            <h6>SEARCH FLIGHTS</h6>
            <h2 class="uk-margin-small-top uk-h1">Search for exactly what you need</h2>
            <form method="POST" action="/flights/search">
              {% csrf_token %}
              {% airport_dropdown 'Source Airport' 'src_air_id' '' %}
              {% airport_dropdown 'Destination Airport' 'dest_air_id' '' %}
              <div class="uk-child-width-1-3" uk-grid>
                <div>
                  <label class="uk-form-label"> Starts after</label>
                  <input class="uk-input uk-border-rounded" type="date" name="start_date">
                </div>
                <div>
                  <label class="uk-form-label">Ends before</label>
                  <input class="uk-input uk-border-rounded" type="date" name="end_date">
                </div>
                <div>
                  <label class="uk-form-label">Max Price</label>
                  <input class="uk-input uk-border-rounded" type="number" name="max_price" value="50000">
                </div>
              </div>
              <div class="uk-text-right uk-padding uk-padding-remove-horizontal">
                <button type="submit" class="uk-button uk-button-primary uk-border-rounded" data-uk-icon="arrow-right"> 
                  Search
                </button>
              </div>
            </form>
            
          </div>
          <div data-uk-scrollspy="cls: uk-animation-fade">
            <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="{% static "img/marketing-2.svg" %}" data-uk-img alt="Image">
          </div>
        </div>
      </div>
    </section>

    <!-- LOGOS -->
    <div class="uk-section uk-section-small uk-section-muted">
      <div class="uk-container uk-container-xlarge">
        <div class="uk-grid uk-child-width-1-4 uk-child-width-expand@m logos-grid" data-uk-grid data-uk-scrollspy="cls: uk-animation-scale-down; target: > div > img; delay: 100">
          {% for airline in  airlines %}
            <div>
            <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/{{airline.upload}}" data-uk-img alt="Image">
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
    <!-- /LOGOS -->
   {% endblock %}

assgn_2/mysite/flights/templates/flights/locations.html
{% extends 'flights/base.html' %}
{% load static%}
{% load flight_inputs %}

{% block content%}
  <div class="uk-container">
    <br>
    <pre><code class="sql"> {{locations.query | sql_format}} </code></pre>

    {% for location in  locations %}
      <article class="uk-article">
          <h1 class="uk-article-title">{{location}}</h1>
          <ul uk-accordion="collapsible: true">
            <li>
                <a class="uk-accordion-title" href="#">Departure</a>
                <div class="uk-accordion-content">
                    {% for airport in  location.airport_set.all %}
                      {% flights_table airport.src_air.all %}
                    {% endfor %}
                </div>
            </li>
            <li>
                <a class="uk-accordion-title" href="#">Arrival</a>
                <div class="uk-accordion-content">
                    {% for airport in  location.airport_set.all %}
                      {% flights_table airport.des_air.all %}
                    {% endfor %}
                </div>
            </li>
        </ul>
      </article>
    {% endfor %}
  </div>
  <br>
{% endblock %}

assgn_2/mysite/flights/templates/flights/search.html
{% extends 'flights/base.html' %}
{% load static%}
{% load flight_inputs %}
{% block header_css %}
	<link rel="stylesheet" type="text/css" href="{% static "css/marketing.css"%}">
{% endblock %}
{% block content%}
    <section class="uk-section uk-section-secondary uk-section-small">
      <div class="uk-container">
        <div>
          <h6>SEARCH FLIGHTS</h6>
          <form method="POST" action="">
            {% csrf_token %}
            <div class="uk-child-width-1-3" uk-grid>
              <div class="uk-width-1-2">
                {% airport_dropdown 'Source Airport' 'src_air_id' form_data.src_air_id %}
              </div>
              <div class="uk-width-1-2">
                {% airport_dropdown 'Destination Airport' 'dest_air_id' form_data.dest_air_id %}
              </div>
              <div class="uk-width-1-4">
                <label class="uk-form-label"> Starts after</label>
                <input class="uk-input uk-border-rounded" type="date" name="start_date" value="{{form_data.start_date}}">
              </div>
              <div class="uk-width-1-4">
                <label class="uk-form-label">Ends before</label>
                <input class="uk-input uk-border-rounded" type="date" name="end_date"
                  value="{{form_data.end_date}}"
                >
              </div>
              <div class="uk-width-1-4">
                <label class="uk-form-label">Max Price</label>
                <input class="uk-input uk-border-rounded" type="number" name="max_price" value="{{form_data.max_price}}">
              </div>
              <div class="uk-width-1-4 uk-text-right">
                <label class="uk-form-label">&nbsp;</label>
                <button type="submit" class="uk-input uk-button uk-button-primary uk-border-rounded" data-uk-icon="arrow-right"> 
                  Search
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </section>
    <div class="uk-container">
      <br>
      <pre><code class="sql"> {{flights.query | sql_format}} </code></pre>
      {% flights_table flights %}
      <br>
    </div>
   {% endblock %}